[package]
name = "sananmuunnos"
version = "0.1.0"
authors = ["Antti Häyrynen <antti.hayrynen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
unicode-segmentation = "1.8.0"
array_tool = "0.2.6"
clap = "2.34.0"
serde = "1.0.132"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.async-std]
version = "1.6"
features = ["attributes", "tokio1"]

[[bin]]
name = "sananmuunnos"
path = "src/main.rs"

[[bin]]
name = "sananmuunnos-webapp"
path = "src/webapp.rs"

